/** Explicit column lists — avoid select("*") pulling megabyte blobs / heavy JSON. */

export const COACH_COLUMNS = [
  "id",
  "user_id",
  "slug",
  "name",
  "first_name",
  "last_name",
  "photo_url",
  "bio",
  "specialization",
  "rate_per_session",
  "session_pricing",
  "court_ids",
  "mobile",
  "instagram",
  "facebook",
  "skill_template_id",
  "coaching_levels",
  "custom_skill_ids",
  "skill_label_overrides",
  "custom_skills",
  "free_trial_enabled",
  "free_trial_weekly_cap",
  "subscription_plan",
  "subscription_expiry",
  "is_active",
  "total_students",
  "total_sessions",
  "created_at",
  "onboarding_completed_at",
].join(", ");

/** Listing cards — skip custom skill payloads. */
export const COACH_LISTING_COLUMNS = [
  "id",
  "slug",
  "name",
  "first_name",
  "last_name",
  "photo_url",
  "bio",
  "specialization",
  "rate_per_session",
  "session_pricing",
  "court_ids",
  "mobile",
  "instagram",
  "facebook",
  "skill_template_id",
  "coaching_levels",
  "free_trial_enabled",
  "free_trial_weekly_cap",
  "subscription_plan",
  "subscription_expiry",
  "is_active",
  "total_students",
  "total_sessions",
  "created_at",
  "onboarding_completed_at",
].join(", ");

export const SESSION_LIST_COLUMNS = [
  "id",
  "coach_id",
  "student_id",
  "type",
  "program_id",
  "session_number",
  "date",
  "time",
  "end_time",
  "court_id",
  "status",
  "payment_status",
  "price",
  "tip",
  "player_count",
  "participants",
  "notes",
  // Ratings kept for lifecycle / wrap-up in the date window (still far smaller than all-time *).
  "ratings_before",
  "ratings_after",
  "participant_progress",
].join(", ");

export const SESSION_DETAIL_COLUMNS = SESSION_LIST_COLUMNS;

export const COURT_COLUMNS = [
  "id",
  "name",
  "address",
  "city",
  "region",
  "maps_url",
  "is_active",
].join(", ");

export const ADMIN_COACH_SUMMARY_COLUMNS = [
  "id",
  "slug",
  "name",
  "first_name",
  "last_name",
  "photo_url",
  "court_ids",
  "subscription_plan",
  "subscription_expiry",
  "is_active",
  "total_students",
  "total_sessions",
  "created_at",
  "onboarding_completed_at",
  "rate_per_session",
  "session_pricing",
  "skill_template_id",
  "coaching_levels",
  "bio",
  "specialization",
  "mobile",
  "instagram",
  "facebook",
  "user_id",
  "custom_skill_ids",
  "skill_label_overrides",
  "custom_skills",
  "free_trial_enabled",
  "free_trial_weekly_cap",
].join(", ");

/** Admin dashboard session aggregates — money/status only, no ratings JSON. */
export const ADMIN_SESSION_AGG_COLUMNS = [
  "id",
  "coach_id",
  "date",
  "status",
  "payment_status",
  "price",
  "tip",
].join(", ");

export const ADMIN_STUDENT_AGG_COLUMNS = ["id", "coach_id", "is_archived"].join(", ");
